#!/bin/bash
DNS_NAME=$(aws ec2 describe-instances --instance-ids i-01f10b6b87b354c40 --query 'Reservations[0].Instances[0].PublicDnsName' --output text)
ssh -i /home/smiel/Documents/aws/shayne_16_09.pem ubuntu@$DNS_NAME
