#!/bin/bash
DNS_NAME=$(aws ec2 describe-instances --instance-ids i-052ca437ac5bcf6e4 --query 'Reservations[0].Instances[0].PublicDnsName' --output text)
ssh -i /home/smiel/Documents/aws/shayne_16_09.pem ubuntu@$DNS_NAME
