#! /bin/bash
aws s3 cp /research/ella/nativeness/test.csv s3://smiel/ella/nativeness/test.csv
aws s3 cp /research/ella/nativeness/train.csv s3://smiel/ella/nativeness/train.csv
aws s3 cp /research/ella/nativeness/dev.csv s3://smiel/ella/nativeness/dev.csv
